name: self_finance
description: "The Self-finance app is a mobile application designed to streamline financial operations for shopkeepers and small finance companies. This solution empowers users with tools to manage their daily transactions and customer accounts efficiently."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.6.3+0

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  drift: ^2.31.0  
  drift_flutter: ^0.2.8
  flutter_email_sender: ^8.0.0
  responsive_sizer: ^3.3.1
  url_launcher: ^6.3.2
  pinput: ^6.0.1
  path_provider: ^2.1.5
  local_auth: ^3.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  photo_view: ^0.15.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  currency_picker: ^2.0.21
  share_plus: ^12.0.1
  feedback: ^3.2.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  path: ^1.9.1
  signature: ^6.3.0
  uuid: ^4.5.2
  archive: ^4.0.7
  file_picker: ^10.3.8
  restart_app: ^1.3.1
  pdf: ^3.10.4
  flutter_dotenv: ^6.0.0
  flutter_slidable: ^4.0.3
  timeline_tile: ^2.0.0
  flutter_local_notifications: ^21.0.0-dev.1
  timezone: ^0.11.0
  flutter_timezone: ^5.0.1
  shared_preferences: ^2.5.4
  flutter_exit_app: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.7
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  analyzer: ^8.4.0
  drift_dev: ^2.31.0


analyzer:
  plugins:
    - custom_lint



flutter:
  uses-material-design: true

  assets:
    - assets/icon/defaultImage.png
    - assets/icon/item_icon.png
    - assets/icon/id_proof_icon.png
    - assets/icon/icon_only.png
    - assets/fonts/
    - .env

  fonts:
    - family: hell
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          style: normal
        - asset: assets/fonts/Helvetica-Oblique.ttf
          style: italic
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: assets/fonts/helvetica-light.ttf
          weight: 300
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
          weight: 700
          style: italic
