name: self_finance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+25

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_email_sender: ^8.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  responsive_sizer: ^3.3.1
  url_launcher: ^6.3.2
  pinput: ^6.0.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  local_auth: ^3.0.0
  flutter_svg_provider: ^1.0.7
  intl: ^0.20.2
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  photo_view: ^0.15.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  liquid_pull_to_refresh: ^3.0.1
  currency_picker: ^2.0.21
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  feedback: ^3.2.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  path: ^1.9.1
  syncfusion_flutter_signaturepad: ^31.2.18
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.7
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  analyzer: ^7.3.0

analyzer:
  plugins:
    - custom_lint

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#000"
  adaptive_icon_foreground: "assets/icon/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: hell
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          style: normal
        - asset: assets/fonts/Helvetica-Oblique.ttf
          style: italic
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: assets/fonts/helvetica-light.ttf
          weight: 300
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
          weight: 700
          style: italic
